# Permalinks
permalink: pretty

# Settings
markdown:  kramdown
destination: ./_site
exclude: ["README.md"]
pagination:
  enabled: true
  per_page: 10
  sort_reverse: true
encoding: UTF-8
future: false
name: Beautiful Open
url: https://beautifulopen.com
description: "Handsome sites for open source"

plugins:
  - jekyll-paginate-v2